version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: ortho_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: ortho_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend/
    container_name: ortho_backend
    image: agasan/ortho_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    environment:
      - DJANGO_SETTINGS_MODULE=orthodontist_site.settings.docker
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend/
    container_name: ortho_frontend
    image: agasan/ortho_frontend
    env_file: .env.frontend
    depends_on:
      - backend
    ports:
    - "3000:3000"

  gateway:
    build: ./nginx/
    container_name: ortho_nginx
    image: agasan/ortho_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - static:/static/
      - media:/app/media/
