# Generated by Django 5.1.1 on 2024-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактная информация')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='static/patient_photos/', verbose_name='Фотографии')),
                ('general_info', models.TextField(verbose_name='Общая информация о пациенте')),
                ('treatment_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип лечения')),
                ('treatment_status', models.CharField(choices=[('initial_consultation', 'Первичная консультация'), ('treatment_started', 'Лечение начато'), ('treatment_completed', 'Лечение завершено')], default='initial_consultation', max_length=100, verbose_name='Статус лечения')),
                ('start_date', models.DateField(verbose_name='Дата начала лечения')),
                ('last_visit_date', models.DateField(verbose_name='Дата последнего визита')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='Следующий визит')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарии врача')),
                ('cost_of_treatment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость лечения')),
            ],
        ),
    ]
