server {
  listen 80;
  
  client_max_body_size 10M;
  
  # Прокидываем /admin/ -> backend:8000/admin/
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/admin/;
  }

  # Прокидываем /api/ -> backend
  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/api/;
  }

  # Прокидываем /media/ -> backend
  location /media/ {
    alias /app/media/;
    try_files $uri =404;
	}

  # /static/ -> volume
  location /static/ {
    alias /static/;
    try_files $uri =404;
  }

  # всё остальное -> фронт (React/Next)
  location / {
    proxy_pass http://frontend:3000;
  }
}
