# Generated by Django 5.1.4 on 2025-02-05 10:06

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Основной текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Предпочтительная дата')),
                ('status', models.CharField(choices=[('new', 'Новая запись'), ('repeat', 'Повторная запись'), ('confirmed', 'Подтверждено'), ('done', 'Завершено'), ('canceled', 'Отменено')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('start_treatment_date', models.DateField(blank=True, null=True, verbose_name='Дата начала лечения')),
                ('end_treatment_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания лечения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('initial_service_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стартовая стоимость услуг')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплачено')),
                ('status', models.CharField(choices=[('new', 'Новый пациент'), ('in_progress', 'В процессе'), ('completed', 'Лечение окончено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_avatars', to=settings.FILER_IMAGE_MODEL, verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.patient')),
            ],
            options={
                'verbose_name': 'дополнительное изображение',
                'verbose_name_plural': 'дополнительные изображения',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Наши работы',
                'verbose_name_plural': 'Наши работы',
            },
        ),
    ]
