# Generated by Django 5.1.4 on 2026-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="patient",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Telegram username"
            ),
        ),
    ]
