# Generated by Django 5.1.4 on 2025-02-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_amount_paid_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('new', 'Новый пациент'), ('in_progress', 'В процессе'), ('completed', 'Лечение окончено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
