# Generated by Django 5.1.4 on 2026-05-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_patient_is_active_patient_telegram_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="core.patient",
                verbose_name="Пациент",
            ),
        ),
    ]
