# Generated by Django 5.1.4 on 2026-05-15 06:40

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_appointment_patient"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок главного блока"
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True, verbose_name="Описание главного блока"
                    ),
                ),
                (
                    "hero_button_text",
                    models.CharField(
                        default="Записаться на консультацию",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "hero_button_url",
                    models.CharField(
                        default="/appointment",
                        max_length=200,
                        verbose_name="Ссылка кнопки",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Заголовок блока о клинике",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(blank=True, verbose_name="Текст блока о клинике"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_hero_images",
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="Картинка главного блока",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
    ]
