# Generated by Django 5.1.4 on 2026-05-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_bullet_1",
            field=models.CharField(
                default="Команда высококвалифицированных специалистов",
                max_length=255,
                verbose_name="Пункт 1",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_bullet_2",
            field=models.CharField(
                default="Индивидуальный подход к каждому пациенту",
                max_length=255,
                verbose_name="Пункт 2",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_bullet_3",
            field=models.CharField(
                default="Использование современного оборудования",
                max_length=255,
                verbose_name="Пункт 3",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_bullet_4",
            field=models.CharField(
                default="Комфортные условия лечения",
                max_length=255,
                verbose_name="Пункт 4",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="feature_1_description",
            field=models.TextField(
                default="Используем современные технологии для визуализации результатов до начала лечения",
                verbose_name="Преимущество 1 - описание",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="feature_1_title",
            field=models.CharField(
                default="3D-планирование лечения",
                max_length=200,
                verbose_name="Преимущество 1 - заголовок",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="feature_2_description",
            field=models.TextField(
                default="Забудьте о неприятных процедурах. Используем только цифровые сканеры",
                verbose_name="Преимущество 2 - описание",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="feature_2_title",
            field=models.CharField(
                default="Цифровые оттиски",
                max_length=200,
                verbose_name="Преимущество 2 - заголовок",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="feature_3_description",
            field=models.TextField(
                default="Первичная консультация возможна онлайн. Экономьте своё время",
                verbose_name="Преимущество 3 - описание",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="feature_3_title",
            field=models.CharField(
                default="Виртуальная консультация",
                max_length=200,
                verbose_name="Преимущество 3 - заголовок",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer_contacts",
            field=models.CharField(
                default="г. Москва, ул. Примерная, д. 1 | Тел: +7 (495) 123-45-67",
                max_length=255,
                verbose_name="Адрес и телефон",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer_copyright",
            field=models.CharField(
                default="© 2025 JML ORTHO. Все права защищены.",
                max_length=255,
                verbose_name="Копирайт",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer_description",
            field=models.CharField(
                default="Профессиональная ортодонтическая клиника",
                max_length=255,
                verbose_name="Описание в футере",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer_title",
            field=models.CharField(
                default="JML ORTHO", max_length=100, verbose_name="Название в футере"
            ),
        ),
    ]
