# Generated by Django 5.1.4 on 2026-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_homepage_about_bullet_1_homepage_about_bullet_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Ссылка на Instagram",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="telegram_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Ссылка на Telegram",
            ),
        ),
    ]
