# Generated by Django 5.1.4 on 2026-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_homepage_instagram_url_homepage_telegram_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="team_text",
            field=models.TextField(
                blank=True,
                default="Наши специалисты регулярно проходят обучение и стажировки в ведущих клиниках мира, чтобы предоставлять вам лечение на высочайшем уровне.",
                verbose_name="Команда - текст",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="team_title",
            field=models.CharField(
                blank=True,
                default="Наша команда",
                max_length=200,
                verbose_name="Команда - заголовок",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="value_1_description",
            field=models.TextField(
                blank=True,
                default="Постоянное совершенствование навыков и применение передовых методик",
                verbose_name="Ценность 1 - описание",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="value_1_title",
            field=models.CharField(
                blank=True,
                default="Профессионализм",
                max_length=200,
                verbose_name="Ценность 1 - заголовок",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="value_2_description",
            field=models.TextField(
                blank=True,
                default="Использование современного оборудования и цифровых технологий",
                verbose_name="Ценность 2 - описание",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="value_2_title",
            field=models.CharField(
                blank=True,
                default="Инновации",
                max_length=200,
                verbose_name="Ценность 2 - заголовок",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="value_3_description",
            field=models.TextField(
                blank=True,
                default="Индивидуальный подход и внимание к каждому пациенту",
                verbose_name="Ценность 3 - описание",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="value_3_title",
            field=models.CharField(
                blank=True,
                default="Забота",
                max_length=200,
                verbose_name="Ценность 3 - заголовок",
            ),
        ),
    ]
