# Generated by Django 5.1.4 on 2026-05-19 09:40

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations

def clear_old_image_values(apps, schema_editor):
    AboutPage = apps.get_model("core", "AboutPage")
    TeamMember = apps.get_model("core", "TeamMember")

    AboutPage.objects.update(image=None)
    TeamMember.objects.update(photo=None)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_teammember"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_old_image_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="aboutpage",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="about_page_images",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_member_photos",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Фото",
            ),
        ),
    ]
